easy_admin:
    site_name: 'Nova Admin Panel'
    design:
        brand_color: '#1ABC9C'
        assets:
            css:
                - 'bundles/easyadmin/bootstrap-all.css'
            js:
                - 'bundles/easyadmin/bootstrap-all.js'
    entities:
        Product:
            class: App\Entity\Product
            label: 'Продукция'
            list:
                title: '%%entity_label%%'
                fields: [
                    'id', 
                    { property: 'name', label: 'Наименование' }, 
                    { property: 'Manufacturer', label: 'Производитель' },
                    { property: 'Brief', label: 'Инфо' },
                    { property: 'Price', label: 'Цена' }, 
                    { property: 'TopSale', label: 'Топ продаж?' },
                    { property: 'PharmGroup', label: 'Фарм группа' },
                    { property: 'MedicinalForm', label: 'Лекформа' },
                    { property: 'TargetAnimals', label: 'Виды животных'}
                    ]
            new:
                title: '%%entity_label%%'
                fields: [ 
                    { property: 'name', label: 'Наименование' }, 
                    { property: 'Manufacturer', label: 'Производитель' },
                    { property: 'Brief', label: 'Инфо' },
                    { property: 'Price', label: 'Цена' }, 
                    { property: 'TopSale', label: 'Топ продаж?' },
                    { property: 'PharmGroup', label: 'Фарм группа' },
                    { property: 'MedicinalForm', label: 'Лекформа' },
                    { property: 'TargetAnimals', label: 'Виды животных'}
                    ]
        MedicinalForm:
            class: App\Entity\MedicinalForm
            label: 'Лекформы'
            list:
                title: '%%entity_label%%'
                fields: [
                    'id', 
                    { property: 'name', label: 'Наименование' }
                        ]
            new:
                title: '%%entity_label%%'
                fields: [
                    { property: 'name', label: 'Наименование' }
                        ]
        PharmGroup:
            class: App\Entity\PharmGroup
            label: 'Фарм группы'
            list:
                title: '%%entity_label%%'
                fields: [
                    'id', 
                    { property: 'name', label: 'Наименование' }
                        ]
            new:
                title: '%%entity_label%%'
                fields: [
                    { property: 'name', label: 'Наименование' }
                        ]
        TargetAnimals:
            class: App\Entity\TargetAnimals
            label: 'Виды животных'
            list:
                title: '%%entity_label%%'
                fields: [
                    'id', 
                    { property: 'name', label: 'Наименование' }
                        ]
            new:
                title: '%%entity_label%%'
                fields: [
                    { property: 'name', label: 'Наименование' }
                        ]
        User:
            class: App\Entity\User
            label: 'Пользователи'
            list:
                title: '%%entity_label%%'
