easy_admin:
    site_name: 'Nova Admin Panel'
    design:
        brand_color: '#1ABC9C'
        assets:
            css:
                - 'css/bootstrap-all.css'
            js:
                - 'js/bootstrap-all.js'
    entities:
        Product:
            class: App\Entity\Product
            label: 'Продукция'
            list:
                title: '%%entity_label%%'
                fields: [
                    'id',
                    { property: 'image', type: 'image', base_path: '/images/products' }, 
                    { property: 'name', label: 'Наименование' }, 
                    { property: 'Manufacturer', label: 'Производитель' },
                    { property: 'Brief', label: 'Инфо' },
                    { property: 'Price', label: 'Цена' }, 
                    { property: 'TopSale', label: 'Топ продаж?' },
                    { property: 'PharmGroup', label: 'Фарм группа' },
                    { property: 'MedicinalForm', label: 'Лекформа' },
                    { property: 'TargetAnimals', label: 'Виды животных'}
                    ]
            new:
                title: '%%entity_label%%'
                fields: [ 
                    { property: 'imageFile', type: 'vich_image' },
                    { property: 'name', label: 'Наименование' }, 
                    { property: 'Manufacturer', label: 'Производитель' },
                    { property: 'Brief', label: 'Инфо' },
                    { property: 'Price', label: 'Цена' }, 
                    { property: 'TopSale', label: 'Топ продаж?' },
                    { property: 'PharmGroup', label: 'Фарм группа' },
                    { property: 'MedicinalForm', label: 'Лекформа' },
                    { property: 'TargetAnimals', label: 'Виды животных'}
                    ]
            edit:
                title: '%%entity_label%%'
                fields: [ 
                    { property: 'imageFile', type: 'vich_image' },
                    { property: 'name', label: 'Наименование' }, 
                    { property: 'Manufacturer', label: 'Производитель' },
                    { property: 'Brief', label: 'Инфо' },
                    { property: 'Price', label: 'Цена' }, 
                    { property: 'TopSale', label: 'Топ продаж?' },
                    { property: 'PharmGroup', label: 'Фарм группа' },
                    { property: 'MedicinalForm', label: 'Лекформа' },
                    { property: 'TargetAnimals', label: 'Виды животных'}
                    ]
        MedicinalForm:
            class: App\Entity\MedicinalForm
            label: 'Лекформы'
            list:
                title: '%%entity_label%%'
                fields: [
                    'id', 
                    { property: 'name', label: 'Наименование' }
                        ]
            new:
                title: '%%entity_label%%'
                fields: [
                    { property: 'name', label: 'Наименование' }
                        ]
            edit:
                title: '%%entity_label%%'
                fields: [
                    { property: 'name', label: 'Наименование' }
                        ]
        PharmGroup:
            class: App\Entity\PharmGroup
            label: 'Фарм группы'
            list:
                title: '%%entity_label%%'
                fields: [
                    'id', 
                    { property: 'name', label: 'Наименование' }
                        ]
            new:
                title: '%%entity_label%%'
                fields: [
                    { property: 'name', label: 'Наименование' }
                        ]
            edit:
                title: '%%entity_label%%'
                fields: [
                    { property: 'name', label: 'Наименование' }
                        ]
        TargetAnimals:
            class: App\Entity\TargetAnimals
            label: 'Виды животных'
            list:
                title: '%%entity_label%%'
                fields: [
                    'id', 
                    { property: 'name', label: 'Наименование' }
                        ]
            new:
                title: '%%entity_label%%'
                fields: [
                    { property: 'name', label: 'Наименование' }
                        ]
            edit:
                title: '%%entity_label%%'
                fields: [
                    { property: 'name', label: 'Наименование' }
                        ]
        User:
            class: App\Entity\User
            label: 'Пользователи'
            list:
                title: '%%entity_label%%'

        NewsItem:
            class: App\Entity\NewsItem
            label: 'Новости'
            list:
                title: '%%entity_label%%'
                fields: [
                    'id',
                    { property: 'createdAt', label: 'Создано' },
                    { property: 'title', label: 'Заголовок' },
                    { property: 'content', label: 'Сообщение' }
                        ]
            new:
                title: '%%entity_label%%'
                fields: [
                    { property: 'title', label: 'Заголовок' },
                    { property: 'content', label: 'Сообщение' }
                        ]